/* Content data - single source of truth for all portfolio items */
/* eslint-disable */

const CONTENT_DATA = [
  { id: "from-snowflake-to-starrocksapache-iceberg-how-fanatics-cut-9", title: "From Snowflake to StarRocks+Apache Iceberg: How Fanatics Cut 90% of Analytics Cost at 6PB Scale", url: "https://celerdata.com/blog/from-snowflake-to-starrocksapache-iceberg-how-fanatics-cut-90-of-analytics-cost-at-6pb-scale", type: "blog", source: "CelerData Blog", date: "2026-03", tags: ["lakehouse", "starrocks", "case-study", "migration", "iceberg"], featured: true },
  { id: "2026-is-when-open-data-real-time-analytics-and-ai-agents-con", title: "2026 Is When Open Data, Real-Time Analytics and AI Agents Converge", url: "https://celerdata.com/blog/2026-is-when-open-data-real-time-analytics-and-ai-agents-converge", type: "blog", source: "CelerData Blog", date: "2026-01", tags: ["real-time"], featured: true },
  { id: "from-hours-to-seconds-how-yuno-accelerated-customer-facing-a", title: "From Hours to Seconds: How Yuno Accelerated Customer-Facing Analytics By Switching Off Snowflake and Athena", url: "https://celerdata.com/blog/from-hours-to-seconds-how-yuno-accelerated-customer-facing-analytics-by-switching-off-snowflake-and-athena", type: "blog", source: "CelerData Blog", date: "2025-12", tags: ["customer-facing", "case-study", "migration", "performance"], featured: true },
  { id: "starrocks-40-bringing-native-columnar-performance-to-json", title: "StarRocks 4.0: Bringing Native Columnar Performance to JSON", url: "https://celerdata.com/blog/starrocks-4.0-bringing-native-columnar-performance-to-json", type: "blog", source: "CelerData Blog", date: "2025-11", tags: ["starrocks", "performance"], featured: false },
  { id: "starrocks-40-delivering-query-ready-data-to-apache-iceberg", title: "StarRocks 4.0: Delivering Query-Ready Data to Apache Iceberg", url: "https://celerdata.com/blog/starrocks-4.0-delivering-query-ready-data-to-apache-iceberg", type: "blog", source: "CelerData Blog", date: "2025-10", tags: ["lakehouse", "starrocks", "iceberg"], featured: false },
  { id: "announcing-starrocks-40-open-fast-governed", title: "Announcing StarRocks 4.0: Open, Fast, Governed", url: "https://celerdata.com/blog/announcing-starrocks-4.0-open-fast-governed", type: "blog", source: "CelerData Blog", date: "2025-09", tags: ["starrocks"], featured: false },
  { id: "data-skew-in-customer-facing-analytics-the-hidden-cost-behin", title: "Data Skew in Customer-Facing Analytics: The Hidden Cost Behind Latency", url: "https://celerdata.com/blog/data-skew-in-customer-facing-analytics-the-hidden-cost-behind-latency", type: "blog", source: "CelerData Blog", date: "2025-08", tags: ["customer-facing"], featured: false },
  { id: "why-customer-facing-analytics-needs-more-than-just-fast", title: "Why Customer-Facing Analytics Needs More Than Just Fast", url: "https://celerdata.com/blog/why-customer-facing-analytics-needs-more-than-just-fast", type: "blog", source: "CelerData Blog", date: "2025-07", tags: ["customer-facing"], featured: false },
  { id: "customer-facing-analytics-without-denormalizing-everything", title: "Customer-Facing Analytics Without Denormalizing Everything", url: "https://celerdata.com/blog/customer-facing-analytics-without-denormalizing-everything", type: "blog", source: "CelerData Blog", date: "2025-06", tags: ["customer-facing", "denormalization"], featured: false },
  { id: "demandbase-ditches-denormalization-by-switching-off-clickhou", title: "Demandbase Ditches Denormalization By Switching off ClickHouse", url: "https://celerdata.com/blog/demandbase-ditches-denormalization-by-switching-off-clickhouse", type: "blog", source: "CelerData Blog", date: "2025-05", tags: ["clickhouse", "denormalization", "case-study"], featured: false },
  { id: "starrocks-connector-for-tableau-is-now-officially-verified", title: "StarRocks Connector for Tableau is Now Officially Verified", url: "https://celerdata.com/blog/starrocks-connector-for-tableau-is-now-officially-verified", type: "blog", source: "CelerData Blog", date: "2025-04", tags: ["starrocks"], featured: false },
  { id: "celerdata-joins-the-connect-with-confluent-partner-program", title: "CelerData Joins the Connect With Confluent Partner Program", url: "https://celerdata.com/blog/celerdata-joins-the-connect-with-confluent-partner-program", type: "blog", source: "CelerData Blog", date: "2025-03", tags: ["denormalization"], featured: false },
  { id: "celerdata-quarterly-update-automatic-materialized-views-and-", title: "CelerData Quarterly Update: Automatic Materialized Views and More", url: "https://celerdata.com/blog/celerdata-quarterly-update-automatic-materialized-views-and-more", type: "blog", source: "CelerData Blog", date: "2025-02", tags: ["materialized-view"], featured: false },
  { id: "announcing-ga-of-aws-graviton-support-on-celerdata-cloud-byo", title: "Announcing GA of AWS Graviton Support on CelerData Cloud BYOC", url: "https://celerdata.com/blog/announcing-ga-of-aws-graviton-support-on-celerdata-cloud-byoc", type: "blog", source: "CelerData Blog", date: "2025-01", tags: [], featured: false },
  { id: "verisoul-enables-real-time-analytics-by-transitioning-off-bi", title: "Verisoul Enables Real-Time Analytics by Transitioning off BigQuery", url: "https://celerdata.com/blog/verisoul-enables-real-time-analytics-by-transitioning-off-bigquery", type: "blog", source: "CelerData Blog", date: "2024-12", tags: ["real-time", "case-study", "migration"], featured: false },
  { id: "5-brilliant-lakehouse-architectures-from-tencent-wechat-and-", title: "5 Brilliant Lakehouse Architectures from Tencent, WeChat, and More", url: "https://celerdata.com/blog/5-brilliant-lakehouse-architectures-from-tencent-wechat-and-more", type: "blog", source: "CelerData Blog", date: "2024-11", tags: ["lakehouse", "case-study"], featured: false },
  { id: "3-data-lakehouse-predictions-for-2024", title: "3 Data Lakehouse Predictions for 2024", url: "https://celerdata.com/blog/3-data-lakehouse-predictions-for-2024", type: "blog", source: "CelerData Blog", date: "2024-10", tags: ["lakehouse"], featured: false },
  { id: "how-to-seamlessly-accelerate-data-lake-queries", title: "How to Seamlessly Accelerate Data Lake Queries", url: "https://celerdata.com/blog/how-to-seamlessly-accelerate-data-lake-queries", type: "blog", source: "CelerData Blog", date: "2024-09", tags: ["lakehouse", "performance"], featured: false },
  { id: "trino-vs-starrocks-get-data-warehouse-performance-on-the-dat", title: "Trino vs. StarRocks: Get Data Warehouse Performance on the Data Lake", url: "https://celerdata.com/blog/trino-vs-starrocks-how-to-get-data-warehouse-performance-on-the-data-lakehouse", type: "blog", source: "CelerData Blog", date: "2024-08", tags: ["lakehouse", "starrocks", "migration", "performance"], featured: false },
  { id: "why-apache-druid-cant-handle-modern-real-time-analytics", title: "Why Apache Druid Can't Handle Modern Real-Time Analytics", url: "https://celerdata.com/blog/why-apache-druid-cant-handle-modern-real-time-analytics", type: "blog", source: "CelerData Blog", date: "2024-07", tags: ["real-time", "migration"], featured: false },
  { id: "celerdata-x-dbta-go-pipeline-free-with-real-time-analytics", title: "CelerData X DBTA: Go Pipeline-Free With Real-Time Analytics", url: "https://celerdata.com/blog/celerdata-x-dbta-go-pipeline-free-with-real-time-analytics", type: "blog", source: "CelerData Blog", date: "2024-06", tags: ["real-time"], featured: false },
  { id: "ditch-denormalization-in-real-time-analytics-with-joins", title: "Ditch Denormalization in Real-Time Analytics With JOINs", url: "https://celerdata.com/blog/ditch-denormalization-in-real-time-analytics-with-joins", type: "blog", source: "CelerData Blog", date: "2024-05", tags: ["real-time", "denormalization"], featured: false },
  { id: "denormalizing-tables-to-avoid-joins-pros-cons-and-alternativ", title: "Denormalizing Tables To Avoid JOINs: Pros, Cons, and Alternatives", url: "https://celerdata.com/blog/denormalizing-tables-to-avoid-joins-pros-cons-and-alternatives", type: "blog", source: "CelerData Blog", date: "2024-04", tags: ["denormalization"], featured: false },
  { id: "answering-questions-about-starrocks-vs-clickhouse", title: "Answering Questions About StarRocks vs. ClickHouse", url: "https://celerdata.com/blog/answering-questions-about-starrocks-vs.-clickhouse", type: "blog", source: "CelerData Blog", date: "2024-03", tags: ["starrocks", "clickhouse"], featured: false },
  { id: "from-denormalization-to-joins-why-clickhouse-cannot-keep-up", title: "From Denormalization to Joins: Why ClickHouse Cannot Keep Up", url: "https://celerdata.com/blog/from-denormalization-to-joins-why-clickhouse-cannot-keep-up", type: "blog", source: "CelerData Blog", date: "2024-02", tags: ["clickhouse", "denormalization"], featured: false },
  { id: "what-is-user-behavior-analytics", title: "What Is User Behavior Analytics?", url: "https://celerdata.com/blog/what-is-user-behavior-analytics", type: "blog", source: "CelerData Blog", date: "2024-01", tags: [], featured: false },
  { id: "what-is-real-time-analytics", title: "What Is Real-Time Analytics?", url: "https://celerdata.com/blog/what-is-real-time-analytics", type: "blog", source: "CelerData Blog", date: "2023-12", tags: ["real-time"], featured: false },
  { id: "why-achieving-real-time-user-facing-analytics-is-hard", title: "Why Achieving Real-Time User-Facing Analytics Is Hard", url: "https://celerdata.com/blog/why-achieving-real-time-user-facing-analytics-is-hard", type: "blog", source: "CelerData Blog", date: "2023-11", tags: ["real-time", "customer-facing"], featured: false },
  { id: "how-expensive-is-real-time-analytics", title: "How Expensive is Real-Time Analytics?", url: "https://celerdata.com/blog/how-expensive-is-real-time-analytics", type: "blog", source: "CelerData Blog", date: "2023-10", tags: ["real-time"], featured: false },
  { id: "how-real-time-analytics-works-a-step-by-step-breakdown", title: "How Real-Time Analytics Works: A Step-by-Step Breakdown", url: "https://celerdata.com/blog/how-real-time-analytics-works-a-step-by-step-breakdown", type: "blog", source: "CelerData Blog", date: "2023-09", tags: ["real-time"], featured: false },
  { id: "what-is-user-facing-analytics", title: "What Is User-Facing Analytics?", url: "https://celerdata.com/blog/what-is-user-facing-analytics", type: "blog", source: "CelerData Blog", date: "2023-08", tags: ["customer-facing"], featured: false },
  { id: "is-join-a-luxury-in-real-time-analytics", title: "Is JOIN a Luxury in Real-Time Analytics?", url: "https://celerdata.com/blog/is-join-a-luxury-in-real-time-analytics", type: "blog", source: "CelerData Blog", date: "2023-07", tags: ["real-time", "denormalization"], featured: false },
  { id: "how-to-simplify-your-real-time-analytics-pipeline", title: "How To Simplify Your Real-Time Analytics Pipeline", url: "https://celerdata.com/blog/how-to-simplify-your-real-time-analytics-pipeline", type: "blog", source: "CelerData Blog", date: "2023-06", tags: ["real-time"], featured: false },
  { id: "is-real-time-analytics-worth-the-real-time-cost", title: "Is Real-Time Analytics Worth the Real-Time Cost?", url: "https://celerdata.com/blog/is-real-time-analytics-worth-the-real-time-cost", type: "blog", source: "CelerData Blog", date: "2023-05", tags: ["real-time"], featured: false },
  { id: "real-time-analytics-is-it-really-for-everyone", title: "Real-Time Analytics: Is It Really for Everyone?", url: "https://celerdata.com/blog/real-time-analytics-is-it-really-for-everyone", type: "blog", source: "CelerData Blog", date: "2023-04", tags: ["real-time"], featured: false },
  { id: "debunking-the-biggest-myths-about-real-time-analytics", title: "Debunking The Biggest Myths About Real-Time Analytics", url: "https://celerdata.com/blog/debunking-the-biggest-myths-about-real-time-analytics", type: "blog", source: "CelerData Blog", date: "2023-03", tags: ["real-time"], featured: false },
  { id: "starrocks-a-game-changer-in-real-time-analytics", title: "StarRocks: A Game-Changer in Real-Time Analytics", url: "https://celerdata.com/blog/starrocks-a-game-changer-in-real-time-analytics", type: "blog", source: "CelerData Blog", date: "2023-02", tags: ["real-time", "starrocks"], featured: false },
  { id: "real-time-analytics-for-the-modern-enterprise", title: "Real-Time Analytics for the Modern Enterprise", url: "https://celerdata.com/blog/real-time-analytics-for-the-modern-enterprise", type: "blog", source: "CelerData Blog", date: "2023-01", tags: ["real-time"], featured: false },
  { id: "delivering-faster-analytics-at-pinterest", title: "Delivering Faster Analytics at Pinterest", url: "https://www.starrocks.io/blog/delivering-faster-analytics-at-pinterest", type: "blog", source: "StarRocks Blog", date: "2026-01", tags: ["case-study", "performance"], featured: true },
  { id: "how-didi-transformed-real-time-risk-engineering-with-starroc", title: "How DiDi Transformed Real-Time Risk Engineering with StarRocks", url: "https://www.starrocks.io/blog/how-didi-transformed-real-time-risk-engineering-with-starrocks", type: "blog", source: "StarRocks Blog", date: "2025-12", tags: ["real-time", "starrocks", "case-study"], featured: true },
  { id: "customer-facing-analytics-meets-agents-eightfolds-move-from-", title: "Customer-Facing Analytics Meets Agents: Eightfold's Move from Redshift to StarRocks", url: "https://www.starrocks.io/blog/customer-facing-analytics-meets-agents-eightfolds-move-from-redshift-to-starrocks", type: "blog", source: "StarRocks Blog", date: "2025-11", tags: ["customer-facing", "starrocks", "case-study", "migration"], featured: true },
  { id: "analytical-agents-new-challenges-for-the-underlying-data-inf", title: "Analytical Agents \u2014 New Challenges for the Underlying Data Infrastructure", url: "https://www.starrocks.io/blog/analytical-agents-new-challenges-for-the-underlying-data-infrastructure", type: "blog", source: "StarRocks Blog", date: "2025-10", tags: [], featured: false },
  { id: "35-webinar-qa-recap-starrocks-security-iceberg-support-and-m", title: "3.5 Webinar Q&A Recap: StarRocks Security, Iceberg Support, and More", url: "https://www.starrocks.io/blog/35-webinar-qa-recap-starrocks-security-iceberg-support-and-more", type: "blog", source: "StarRocks Blog", date: "2025-09", tags: ["lakehouse", "starrocks", "iceberg"], featured: false },
  { id: "introducing-starrocks-35", title: "Introducing StarRocks 3.5", url: "https://www.starrocks.io/blog/introducing-starrocks-3-5", type: "blog", source: "StarRocks Blog", date: "2025-08", tags: ["starrocks"], featured: false },
  { id: "introducing-starrocks-34", title: "Introducing StarRocks 3.4", url: "https://www.starrocks.io/blog/introducing-starrocks-3.4", type: "blog", source: "StarRocks Blog", date: "2025-07", tags: ["starrocks"], featured: false },
  { id: "accelerate-customer-facing-analytics-on-open-lakehouses-with", title: "Accelerate Customer-Facing Analytics on Open Lakehouses With Caching", url: "https://www.starrocks.io/blog/accelerate-customer-facing-analytics-on-open-lakehouses-with-caching", type: "blog", source: "StarRocks Blog", date: "2025-06", tags: ["lakehouse", "customer-facing", "performance"], featured: false },
  { id: "build-a-more-open-lakehouse-with-unity-catalog", title: "Build a More Open Lakehouse With Unity Catalog", url: "https://www.starrocks.io/blog/build-a-more-open-lakehouse-with-unity-catalog", type: "blog", source: "StarRocks Blog", date: "2025-05", tags: ["lakehouse"], featured: false },
  { id: "how-to-accelerate-iceberg-metadata-retrieval", title: "How to Accelerate Iceberg Metadata Retrieval", url: "https://www.starrocks.io/blog/how-to-accelerate-iceberg-metadata-retrieval", type: "blog", source: "StarRocks Blog", date: "2025-04", tags: ["lakehouse", "iceberg", "performance"], featured: false },
  { id: "the-answer-to-the-data-upsert-challenge-in-real-time-analyti", title: "The Answer to the Data Upsert Challenge in Real-Time Analytics", url: "https://www.starrocks.io/blog/the-answer-to-the-data-upsert-challenge-in-real-time-analytics", type: "blog", source: "StarRocks Blog", date: "2025-03", tags: ["real-time"], featured: false },
  { id: "how-to-accelerate-semi-structured-data-analytics", title: "How To Accelerate Semi-Structured Data Analytics", url: "https://www.starrocks.io/blog/how-to-accelerate-semi-structured-data-analytics", type: "blog", source: "StarRocks Blog", date: "2025-02", tags: ["performance"], featured: false },
  { id: "starrocks-33-is-out-features-and-improvements", title: "StarRocks 3.3 Is Out: Features and Improvements", url: "https://www.starrocks.io/blog/starrocks-3.3-is-out-features-and-improvements", type: "blog", source: "StarRocks Blog", date: "2025-01", tags: ["starrocks"], featured: false },
  { id: "a-top-social-app-boosts-query-speeds-on-its-exabyte-scale-da", title: "A Top Social App Boosts Query Speeds on Its Exabyte-Scale Data Lake", url: "https://www.starrocks.io/blog/a-top-social-app-boosts-query-speeds-on-its-exabyte-scale-data-lake", type: "blog", source: "StarRocks Blog", date: "2024-11", tags: ["lakehouse", "performance"], featured: false },
  { id: "how-wechats-lakehouse-design-efficiently-handles-trillions-o", title: "How WeChat's Lakehouse Design Efficiently Handles Trillions of Records", url: "https://www.starrocks.io/blog/how-wechats-data-lakehouse-architecture-enhances-efficiency-for-trillions-of-daily-records", type: "blog", source: "StarRocks Blog", date: "2024-09", tags: ["lakehouse", "case-study"], featured: false },
  { id: "tencents-ab-test-platform-unifies-all-sql-workloads-on-the-l", title: "Tencent's A/B Test Platform Unifies All SQL Workloads On The Lakehouse", url: "https://www.starrocks.io/blog/tencents-abetterchoice-platform-unifies-all-sql-workloads-on-the-data-lakehouse", type: "blog", source: "StarRocks Blog", date: "2024-07", tags: ["lakehouse", "case-study"], featured: false },
  { id: "tripcom-ditches-their-data-warehouse-with-starrocks", title: "Trip.com Ditches Their Data Warehouse With StarRocks", url: "https://www.starrocks.io/blog/trip.com-ditches-their-data-warehouse-with-starrocks", type: "blog", source: "StarRocks Blog", date: "2024-05", tags: ["starrocks", "case-study"], featured: false },
  { id: "tencent-unifies-their-gaming-analytics-with-starrocks", title: "Tencent Unifies Their Gaming Analytics With StarRocks", url: "https://www.starrocks.io/blog/tencent-unifies-their-gaming-analytics-with-starrocks", type: "blog", source: "StarRocks Blog", date: "2024-03", tags: ["starrocks", "case-study"], featured: false },
  { id: "high-concurrency-olap-workloads-with-starrocks-query-cache", title: "High-Concurrency OLAP Workloads with StarRocks Query Cache", url: "https://www.starrocks.io/blog/starrocks-olap-workloads-with-starrocks-query-cache", type: "blog", source: "StarRocks Blog", date: "2024-01", tags: ["starrocks"], featured: false },
  { id: "the-open-data-lakehouse-towards-democratized-data-analytics", title: "The Open Data Lakehouse: Towards Democratized Data Analytics", url: "https://www.starrocks.io/blog/the-open-data-lakehouse-democratized-data-analytics", type: "blog", source: "StarRocks Blog", date: "2023-10", tags: ["lakehouse"], featured: false },
  { id: "databricks-iceberg-managed-table-explained", title: "Databricks Iceberg Managed Table Explained", url: "https://medium.com/starrocks-engineering/databricks-iceberg-managed-table-explained-8b86551b2703", type: "blog", source: "Medium", date: "2024-09", tags: ["lakehouse", "iceberg"], featured: true },
  { id: "rockset-is-acquired-by-openai-what-does-it-mean-for-its-user", title: "Rockset Is Acquired by OpenAI. What Does It Mean for Its Users?", url: "https://medium.com/starrocks-engineering/rockset-is-acquired-by-openai-what-does-it-mean-for-its-users-3fa9561979d2", type: "blog", source: "Medium", date: "2024-07", tags: ["migration"], featured: true },
  { id: "detailed-comparison-between-starrocks-and-apache-doris", title: "Detailed Comparison Between StarRocks and Apache Doris", url: "https://medium.com/starrocks-engineering/detailed-comparison-between-starrocks-and-apache-doris-81ddd34be527", type: "blog", source: "Medium", date: "2024-03", tags: ["starrocks"], featured: true },
  { id: "recap-of-the-starrocks-30-community-call-feature-highlights-", title: "Recap of the StarRocks 3.0 Community Call \u2014 Feature Highlights and Q&A", url: "https://medium.com/starrocks-engineering/recap-of-the-starrocks-3-0-community-call-feature-highlights-and-q-a-e6f71ea3e7b2", type: "blog", source: "Medium", date: "2023-06", tags: ["starrocks"], featured: false },
  { id: "delta-kernel-a-game-changer-for-customer-facing-analytics", title: "Delta Kernel: A Game-Changer for Customer-Facing Analytics", url: "https://delta.io/blog/starrocks-kernel/", type: "blog", source: "delta.io", date: "2022-01", tags: ["lakehouse", "customer-facing"], featured: true },
  { id: "how-to-get-data-warehouse-performance-on-the-data-lakehouse", title: "How to Get Data Warehouse Performance on the Data Lakehouse", url: "https://thenewstack.io/how-to-get-data-warehouse-performance-on-the-data-lakehouse/", type: "blog", source: "The New Stack", date: "2022-01", tags: ["lakehouse", "performance"], featured: true },
  { id: "whats-pipeline-free-real-time-data-analytics", title: "What's 'Pipeline-Free' Real-Time Data Analytics?", url: "https://thenewstack.io/whats-pipeline-free-real-time-data-analytics/", type: "blog", source: "The New Stack", date: "2022-01", tags: ["real-time"], featured: true },
  { id: "navigating-the-high-concurrency-challenges-of-user-facing-an", title: "Navigating the High-Concurrency Challenges of User-Facing Analytics", url: "https://thenewstack.io/navigating-the-high-concurrency-challenges-of-user-facing-analytics/", type: "blog", source: "The New Stack", date: "2022-01", tags: ["customer-facing"], featured: true },
  { id: "how-to-go-pipeline-free-with-your-real-time-analytics", title: "How to Go Pipeline-Free with Your Real-Time Analytics", url: "https://thenewstack.io/how-to-go-pipeline-free-with-your-real-time-analytics/", type: "blog", source: "The New Stack", date: "2022-01", tags: ["real-time"], featured: false },
  { id: "celerdata-upends-real-time-data-analytics-with-dynamic-table", title: "CelerData Upends Real-Time Data Analytics with Dynamic Table Joins", url: "https://thenewstack.io/celerdata-upends-real-time-data-analytics-with-dynamic-table-joins/", type: "blog", source: "The New Stack", date: "2022-01", tags: ["real-time", "denormalization"], featured: false },
  { id: "the-solution-to-data-in-motion-is-to-just-stop", title: "The Solution to Data in Motion Is to Just Stop", url: "http://insideainews.com/2024/04/22/the-solution-to-data-in-motion-is-to-just-stop/", type: "blog", source: "insideAI News", date: "2022-01", tags: [], featured: true },
  { id: "accelerating-apache-superset-dashboards-with-materialized-vi", title: "Accelerating Apache Superset Dashboards With Materialized Views", url: "https://preset.io/blog/accelerating-apache-superset-dashboards-with-materialized-views/", type: "blog", source: "Preset.io", date: "2022-01", tags: ["materialized-view", "performance"], featured: true },
  { id: "sida-shen-of-celerdata-on-how-to-leverage-data-to-take-your-", title: "Sida Shen of CelerData On How To Leverage Data To Take Your Company To The Next Level", url: "https://medium.com/authority-magazine/sida-shen-of-celerdata-on-how-to-leverage-data-to-take-your-company-to-the-next-level-ce5a1c41d960", type: "interview", source: "Authority Magazine", date: "2022-01", tags: [], featured: true },
  { id: "celerdata-enables-data-engineers-to-build-new-analytics-proj", title: "CelerData Enables Data Engineers To Build New Analytics Projects Faster", url: "https://tfir.io/celerdata-enables-data-engineers-to-build-new-analytics-projects-faster-sida-shen/", type: "interview", source: "TFiR", date: "2022-01", tags: ["performance"], featured: true },
  { id: "celerdata-breaking-the-data-pipeline-for-real-time-analytics", title: "CelerData: Breaking the Data Pipeline for Real-Time Analytics", url: "https://www.truthinit.com/index.php/video/3731/celerdata-breaking-the-data-pipeline-for-real-time-analytics/", type: "interview", source: "Truth in IT", date: "2022-01", tags: ["real-time"], featured: true },
  { id: "starrocks-bridging-lakehouse-and-olap-for-high-performance-a", title: "StarRocks: Bridging Lakehouse and OLAP for High-Performance Analytics", url: "https://www.dataengineeringpodcast.com/episodepage/starrocks-high-performance-lakehouse-and-olap-episode-463", type: "interview", source: "Data Eng Podcast", date: "2022-01", tags: ["lakehouse", "starrocks", "performance"], featured: true },
  { id: "databricks-dataai-summit-2024", title: "Databricks Data+AI Summit 2024", url: "https://www.databricks.com/dataaisummit/speaker/sida-shen", type: "video", source: "Conference", date: "2024-06", tags: [], featured: true },
  { id: "starrocks-summit-2025-announcing-starrocks-40", title: "StarRocks Summit 2025 \u2014 Announcing StarRocks 4.0", url: "https://summit.starrocks.io/2025", type: "video", source: "Conference", date: "2025-01", tags: ["starrocks"], featured: true },
  { id: "starrocks-year-in-review-2024", title: "StarRocks Year-in-Review 2024", url: "https://x.com/StarRocksLabs/status/1879211873788145773", type: "video", source: "Conference", date: "2024-12", tags: ["starrocks"], featured: true },
  { id: "data-warehouse-performance-on-the-data-lakehouse", title: "Data Warehouse Performance on the Data Lakehouse", url: "https://www.youtube.com/watch?v=UTRcEqcTx4g", type: "video", source: "Webinar", date: "2025-12", tags: ["lakehouse", "performance"], featured: true },
  { id: "how-conductor-builds-sub-second-agentic-analytics-at-scale", title: "How Conductor Builds Sub Second Agentic Analytics at Scale", url: "https://www.youtube.com/watch?v=36pZag6KKcs", type: "video", source: "Webinar", date: "2025-11", tags: ["case-study"], featured: true },
  { id: "apache-iceberg-starrocks-your-recipe-for-superior-lakehouse-", title: "Apache Iceberg + StarRocks: Your Recipe for Superior Lakehouse Performance", url: "https://www.youtube.com/watch?v=8Q5Vev4O1lQ", type: "video", source: "Webinar", date: "2025-10", tags: ["lakehouse", "starrocks", "iceberg", "performance"], featured: true },
  { id: "customer-facing-analytics-how-to-choose-a-real-time-cloud-da", title: "Customer Facing Analytics: How to Choose a Real Time Cloud Data Warehouse", url: "https://www.youtube.com/watch?v=4OBZc45OoNg", type: "video", source: "Webinar", date: "2025-09", tags: ["real-time", "customer-facing"], featured: false },
  { id: "from-denormalization-to-joins-why-clickhouse-cant-keep-up", title: "From Denormalization to JOINS: Why ClickHouse Can't Keep Up", url: "https://www.youtube.com/watch?v=1xvFZskEp1o", type: "video", source: "Webinar", date: "2025-08", tags: ["clickhouse", "denormalization"], featured: false },
  { id: "whats-next-for-lakehouse-in-2025-with-databricks-and-celerda", title: "What's Next for Lakehouse in 2025 With Databricks and CelerData", url: "https://www.youtube.com/watch?v=KyyVBzjP6A0", type: "video", source: "Webinar", date: "2025-07", tags: ["lakehouse"], featured: false },
  { id: "why-customer-facing-analytics-breaksand-how-to-build-it-righ", title: "Why Customer-Facing Analytics Breaks\u2014and How to Build It Right", url: "https://www.youtube.com/watch?v=6SRBUrW1MOc", type: "video", source: "Webinar", date: "2025-06", tags: ["customer-facing"], featured: false },
  { id: "introducing-starrocks-34-2", title: "Introducing StarRocks 3.4", url: "https://www.youtube.com/watch?v=NHi-0QpMXBA", type: "video", source: "Webinar", date: "2025-05", tags: ["starrocks"], featured: false },
  { id: "stream-processing-must-haves", title: "Stream Processing Must Haves", url: "https://www.youtube.com/watch?v=WpHGIPwE1is", type: "video", source: "Webinar", date: "2025-04", tags: [], featured: false },
  { id: "celerdata-quarterly-update-automatic-materialized-views-and--2", title: "CelerData Quarterly Update: Automatic Materialized Views and More", url: "https://www.youtube.com/watch?v=r_b8dyKvf1I", type: "video", source: "Webinar", date: "2025-03", tags: ["materialized-view"], featured: false },
  { id: "zero-to-hero-customer-facing-analytics-on-lakehouse-in-under", title: "Zero to Hero: Customer-Facing Analytics on Lakehouse in Under an Hour", url: "https://www.youtube.com/watch?v=mu9ZqDSqJ44", type: "video", source: "Webinar", date: "2025-02", tags: ["lakehouse", "customer-facing"], featured: false },
  { id: "demandbase-ditches-denormalization-by-switching-off-clickhou-2", title: "Demandbase Ditches Denormalization By Switching off ClickHouse", url: "https://www.youtube.com/watch?v=yqmnboDFyLA", type: "video", source: "Webinar", date: "2025-01", tags: ["clickhouse", "denormalization", "case-study"], featured: false },
  { id: "starrocks-33-is-here-key-features-and-improvements", title: "StarRocks 3.3 is Here: Key Features and Improvements", url: "https://www.youtube.com/watch?v=8Bpn4wkY9lY", type: "video", source: "Webinar", date: "2024-12", tags: ["starrocks"], featured: false },
  { id: "xiaohongshurednotes-secret-for-customer-facing-analytics-wit", title: "Xiaohongshu/RedNote's Secret for Customer-Facing Analytics With 200M+ Users", url: "https://www.youtube.com/watch?v=2cvIZY4EDak", type: "video", source: "Webinar", date: "2024-11", tags: ["customer-facing", "case-study"], featured: false },
  { id: "celerdata-enables-data-engineers-to-build-new-analytics-proj-2", title: "CelerData Enables Data Engineers To Build New Analytics Projects Faster (TFiR)", url: "https://www.youtube.com/watch?v=EMsYkabJVpQ", type: "video", source: "Webinar", date: "2024-10", tags: ["performance"], featured: false },
  { id: "introducing-starrocks-35-2", title: "Introducing StarRocks 3.5", url: "https://www.youtube.com/watch?v=K8Ji1uWws8A", type: "video", source: "Webinar", date: "2024-09", tags: ["starrocks"], featured: false },
  { id: "engineering-insights-from-pinterest-customer-facing-analytic", title: "Engineering Insights from Pinterest: Customer-Facing Analytics that Pays", url: "https://www.youtube.com/watch?v=lK2YeiT8OX4", type: "video", source: "Webinar", date: "2024-08", tags: ["customer-facing", "case-study"], featured: false },
  { id: "customer-facing-analytics-meets-agents-eightfolds-journey-be", title: "Customer-Facing Analytics Meets Agents: Eightfold's Journey Beyond Redshift", url: "https://www.youtube.com/watch?v=qNk_-QTZk3E", type: "video", source: "Webinar", date: "2024-07", tags: ["customer-facing", "case-study", "migration"], featured: false },
  { id: "5-brilliant-lakehouse-architectures-from-tencent-wechat-and--2", title: "5 Brilliant Lakehouse Architectures from Tencent, WeChat, and More", url: "https://www.youtube.com/watch?v=2Hhrn2jPSRk", type: "video", source: "Webinar", date: "2024-06", tags: ["lakehouse", "case-study"], featured: false },
  { id: "query-engine-must-haves-for-the-best-apache-superset-experie", title: "Query Engine Must-Haves for the Best Apache Superset Experience", url: "https://www.youtube.com/watch?v=rHZTBbZOgWM", type: "video", source: "Webinar", date: "2024-05", tags: [], featured: false },
  { id: "bringing-data-warehouse-performance-to-apache-iceberg", title: "Bringing Data Warehouse Performance to Apache Iceberg", url: "https://www.youtube.com/watch?v=UoGbJS0CHHw", type: "video", source: "Webinar", date: "2024-04", tags: ["lakehouse", "iceberg", "performance"], featured: false },
  { id: "governed-fast-and-open-better-customer-facing-with-unity-cat", title: "Governed, Fast, and Open: Better Customer-Facing With Unity Catalog", url: "https://www.youtube.com/watch?v=jEmyWWFvBi8", type: "video", source: "Webinar", date: "2024-03", tags: ["customer-facing"], featured: false },
  { id: "real-time-analytics-for-web3-fraud-detection-trading-and-gro", title: "Real-Time Analytics for Web3: Fraud Detection, Trading, and Growth at Scale", url: "https://www.youtube.com/watch?v=_MkcCgvYmw8", type: "video", source: "Webinar", date: "2024-02", tags: ["real-time"], featured: false },
  { id: "starrocks-bridging-lakehouse-and-olap-for-high-performance-a-2", title: "StarRocks: Bridging Lakehouse and OLAP for High-Performance Analytics", url: "https://www.youtube.com/watch?v=_aciC8XCtN4", type: "video", source: "Webinar", date: "2024-01", tags: ["lakehouse", "starrocks", "performance"], featured: false },
  { id: "unity-catalog-community-meetup-spice-integration", title: "Unity Catalog Community Meetup \u2014 Spice Integration", url: "https://www.youtube.com/watch?v=S2Fsb8BoEPI", type: "video", source: "Webinar", date: "2023-12", tags: [], featured: false },
  { id: "what-is-starrocks-features-and-use-cases", title: "What Is StarRocks: Features and Use Cases", url: "https://www.youtube.com/watch?v=RfXO5GOnbW4", type: "video", source: "Webinar", date: "2023-11", tags: ["starrocks"], featured: false },
  { id: "trino-vs-starrocks-how-to-get-data-warehouse-performance-on-", title: "Trino Vs StarRocks \u2014 How to Get Data Warehouse Performance on the Lakehouse", url: "https://www.youtube.com/watch?v=1Ehnmtl60dQ", type: "video", source: "Webinar", date: "2023-10", tags: ["lakehouse", "starrocks", "migration", "performance"], featured: false },
  { id: "ditching-denormalization-in-real-time-analytics-how-starrock", title: "Ditching Denormalization in Real-time Analytics: How StarRocks Delivers Superior JOIN Performance", url: "https://www.youtube.com/watch?v=T1iOZ67jOD8", type: "video", source: "Webinar", date: "2023-09", tags: ["real-time", "starrocks", "denormalization", "performance"], featured: false },
  { id: "starrocks-virtual-meetup-version-33x-and-whats-next", title: "StarRocks Virtual Meetup: Version 3.3.x and What's Next", url: "https://www.youtube.com/watch?v=qs4RQ37h_dI", type: "video", source: "Webinar", date: "2023-08", tags: ["starrocks"], featured: false },
  { id: "the-register-celerdata-ditch-your-data-warehouse-with-superi", title: "The Register & CelerData: Ditch Your Data Warehouse with Superior Lakehouse Performance", url: "https://www.youtube.com/watch?v=fhalIaRVIdU", type: "video", source: "Webinar", date: "2023-07", tags: ["lakehouse", "performance"], featured: false },
  { id: "rockset-acquired-by-openai-whats-next-for-its-users", title: "Rockset Acquired by OpenAI: What's Next for Its Users?", url: "https://www.youtube.com/watch?v=xfnNjsXgYhs", type: "video", source: "Webinar", date: "2023-06", tags: ["migration"], featured: false },
  { id: "starrocks-at-fresha-carving-streams-into-rock", title: "StarRocks at Fresha: Carving Streams into Rock", url: "https://www.youtube.com/watch?v=3jis0HzmD2A", type: "video", source: "Webinar", date: "2023-05", tags: ["starrocks", "case-study"], featured: false },
  { id: "how-to-boost-your-data-lake-performance-with-materialized-vi", title: "How to Boost Your Data Lake Performance with Materialized Views", url: "https://www.youtube.com/watch?v=R3F9MPxZDIY", type: "video", source: "Webinar", date: "2023-04", tags: ["lakehouse", "materialized-view", "performance"], featured: false },
  { id: "whats-new-with-starrocks-30", title: "What's new with StarRocks 3.0", url: "https://www.youtube.com/watch?v=SlNoPXBm4EY", type: "video", source: "Webinar", date: "2023-03", tags: ["starrocks"], featured: false },
  { id: "why-apache-druid-cant-handle-modern-real-time-analytics-and-", title: "Why Apache Druid Can't Handle Modern Real-Time Analytics and What to Do About It", url: "https://www.youtube.com/watch?v=wgJaB_PuHO4", type: "video", source: "Webinar", date: "2023-02", tags: ["real-time", "migration"], featured: false },
  { id: "how-to-make-user-behavior-analytics-work-for-you", title: "How to Make User Behavior Analytics Work for You", url: "https://www.youtube.com/watch?v=8ZhWCRObH6M", type: "video", source: "Webinar", date: "2023-01", tags: [], featured: false },
  { id: "dzone-fireside-chats-how-to-go-pipeline-free-with-real-time-", title: "DZone FireSide Chats: How to Go Pipeline Free With Real Time Analytics", url: "https://www.youtube.com/watch?v=ky6swN5VUG4", type: "video", source: "Webinar", date: "2022-12", tags: ["real-time"], featured: false },
  { id: "user-facing-analytics-ufa-challenges-data-analytics-and-more", title: "User-facing Analytics (UFA), Challenges, Data Analytics and more!", url: "https://www.youtube.com/watch?v=60QCCqjy1OA", type: "video", source: "Webinar", date: "2022-11", tags: ["customer-facing"], featured: false },
  { id: "celerdata-x-dbta-go-pipeline-free-with-real-time-analytics-2", title: "CelerData X DBTA \u2014 Go Pipeline-Free With Real-Time Analytics", url: "https://www.youtube.com/watch?v=CVDorXdpS4Q", type: "video", source: "Webinar", date: "2022-10", tags: ["real-time"], featured: false },
  { id: "how-to-develop-user-facing-analytics-projects-that-scale", title: "How to Develop User Facing Analytics Projects That Scale", url: "https://www.youtube.com/watch?v=_leXtu5IGEs", type: "video", source: "Webinar", date: "2022-09", tags: ["customer-facing"], featured: false },
  { id: "starrocks-on-aws", title: "StarRocks on AWS", url: "https://www.youtube.com/watch?v=TvcXQX0jSGE", type: "video", source: "Webinar", date: "2022-08", tags: ["starrocks"], featured: false },
  { id: "starrocks-virtual-office-hours-whats-new-and-exciting-with-s", title: "StarRocks Virtual Office Hours \u2014 What's New and Exciting with StarRocks 2.4.0", url: "https://www.youtube.com/watch?v=4hWcCQtj9RE", type: "video", source: "Webinar", date: "2022-07", tags: ["starrocks"], featured: false },
];

const ContentUtils = {
  search(keyword) {
    const kw = keyword.toLowerCase();
    return CONTENT_DATA.filter(item =>
      item.title.toLowerCase().includes(kw) ||
      item.tags.some(t => t.toLowerCase().includes(kw)) ||
      item.source.toLowerCase().includes(kw)
    );
  },

  latest(n) {
    n = n || 5;
    return [...CONTENT_DATA].sort((a, b) => b.date.localeCompare(a.date)).slice(0, n);
  },

  countByType() {
    const counts = { blog: 0, video: 0, interview: 0 };
    for (const item of CONTENT_DATA) counts[item.type] = (counts[item.type] || 0) + 1;
    return counts;
  },

  totalCount() { return CONTENT_DATA.length; },

  byType(type) {
    return CONTENT_DATA.filter(item => item.type === type);
  },

  bySource(source) {
    return CONTENT_DATA.filter(item => item.source === source);
  },

  featured() {
    return CONTENT_DATA.filter(item => item.featured);
  },

  sources() {
    const s = {};
    for (const item of CONTENT_DATA) s[item.source] = (s[item.source] || 0) + 1;
    return s;
  },
};
